### ISSUE TITLE
Python Syntax error

### ISSUE THREAD

**Issue by joy282** [wingtk/gtk-win32#104]
I tried to run the command `python .\build.py build gtk3` in the directory C:\gtk-build\github\gtk-win32.
However, it sends out an error saying 
`   File ".\build.py", line 1455
       print("Error:", msg, file-sys.stderr

SyntaxError: invalid syntax`

I'm a beginner in using MSYS, gtk.. could you help me on what I might have done wrong?

**Comment by nacho** [comment]
Are you using python 3?

**Comment by joy282** [comment]
Fixed it! I had python2 and python 3 installed at the same time and it was running on python2.
Thank you!

**Comment by joy282** [comment]
Could I ask one more?

The installation with cmd failed with
`Error: glib build failed` 

Is there anything I could try to fix this?

**Comment by nacho** [comment]
that does not give much, you should check more on the logs and see why it is failing. Did you install all the deps in msys2?

**Comment by joy282** [comment]
I had all these installed. Is there anything else that I have to install?
Visual Studio 2013 Express for Windows Desktop - Any version of VS apart from 2013 is not supported.
CMake 3.0.2 (also works with CMake 2.8.x)
msys2
Perl 5.20 x86 or x64 (extract to C:\perl)
Python 3.4 (install in C:\Python34), or other package like Miniconda 3.4
nuget (install in C:\gtk-build\nuget)

Sorry, I'm new to using command windows and python, I can't find the log file.
I really appreciate your help, I spend the whole week trying to download glib.

**Comment by nacho** [comment]
Yes, see that you need to install in msys2 some packages, it is explained on the README file.
