### ISSUE TITLE
Add support for meson

### ISSUE THREAD

**Issue by nacho** [wingtk/gtk-win32#108]
Some projects like libepoxy and graphene depend or will depend on meson. We should add support for this build system. For this we need to automatically download ninja and meson, see https://github.com/wingtk/gtk-win32/issues/107 and then use meson to build those modules.

**Comment by TingPing** [comment]
> For this we need to automatically download ninja

Why not just build it?

**Comment by nacho** [comment]
That's fine for me as well, just wanted to avoid the overhead of building ninja and meson for each configuration

**Comment by nacho** [comment]
Meson support is already in master. Let's close this, if issues arise we should file other tickets.
