### ISSUE TITLE
Error with tool if building with --no-deps

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gtk-win32#118]
if you run the build with --no-deps flag the tools paths (meson, ninja or nuget) are not loaded and you get an exception, something like: 
Attribute error: 'Builder' object has no attribute 'meson' (or 'ninja' or 'nuget').

**Comment by nacho** [comment]
right, I think those paths i.e gtk_build\tools\tool should be set by default at startup. Then we should check if they exists or not and if --no-deps is not set they will be downloaded and installed.
