### ISSUE TITLE
Error building wing with meson 0.39

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gtk-win32#135]
The wing project cannot be build with the new meson version that complains about trying to form an absolute path to a source dir, a new check in this version (using the same command with meson 0.38.1 work and create the library correctly).

In the long run the solution is to fix the meson.build file but if needed we can use, only for this project, the old version (should be a matter of 10 lines of code, so we can test multiple versions of the same tool).

**Comment by TingPing** [comment]
At a glance the change is here: https://git.gnome.org/browse/wing/tree/wing/meson.build#n46

```diff
-wing_inc = include_directories([ meson.current_source_dir(), meson.current_build_dir(), meson.build_root(), meson.source_root() ])
+wing_inc = include_directories('.')
```

**Comment by nacho** [comment]
@TingPing does that take care of those different paths automatically?

**Comment by TingPing** [comment]
All paths include both the source and build dir variants. You can also include `..` (which is the relative root) but at a glance you both don't use that in tests and you already have defined `core_inc` to use.

**Comment by TingPing** [comment]
Also just worth noting you never need to include `.` in the same file as you do here, it is only needed when other directories use it like tests.

**Comment by nacho** [comment]
can you push a fix to wing?

**Comment by nacho** [comment]
@tingping thanks

**Comment by guruDanny67** [comment]
Now it builds with meson so the issue is to close.
