### ISSUE TITLE
Error building libepoxy 1.4.1 with VS2013

### ISSUE THREAD

**Issue by accel2k** [wingtk/gtk-win32#139]
Building project libepoxy
[1/12] Compiling c object src/epoxy@sha/src_wgl_generated_dispatch.c.obj
FAILED: src/epoxy@sha/src_wgl_generated_dispatch.c.obj
cl @src/epoxy@sha/src_wgl_generated_dispatch.c.obj.rsp
C:\Program Files (x86)\Windows Kits\8.1\include\shared\minwindef.h(130) : warning C4005: APIENTRY: изменение макроопределения
        ..\\include\epoxy/gl.h(59): см. предыдущее определение "APIENTRY"
src/wgl_generated_dispatch.c(162) : error C2054: требуется "(" после "inline"
src/wgl_generated_dispatch.c(163) : error C2085: get_dispatch_table: отсутствует в списке формальных параметров
src/wgl_generated_dispatch.c(168) : error C2057: требуется константное выражение
...

This issue is fixed in upstream https://github.com/anholt/libepoxy/commit/3f932aeb2f635157788c9cbcda280f2ca808c725, but i don't know how to fix this in gtk-win32.

**Comment by nacho** [comment]
@ebassi can u make a new release?

**Comment by accel2k** [comment]
No, i can't. I don't have needed rights. I think Emmanuele Bassi (@ebassi) can.

**Comment by ebassi** [comment]
@nacho Will try to spin a new release at the end of the week.

**Comment by nacho** [comment]
While we do not have the new release I backported the patch. Thanks
