### ISSUE TITLE
MSVC 14 supported

### ISSUE THREAD

**Issue by intity** [wingtk/gtk-win32#17]
Hi,
It seems for MSVC 14 compilation is not supported.

**Comment by pbor** [comment]
Hi, we definetely want to support MSVC14, but we are not using it yet so we do not have a way to test right now.

However Fan's upstream projects already support it and also the hexchat script we forked from recently switched to it so it should be fairly easy to do.

Mostly it will be a matter of adding "vs14" folders for each module and copying the files

**Comment by INTITY** [comment]
Hi pbor,
I managed to compile only part of the library. Here is the result of compilation:
...
The following items were successfully built:
ffmpeg
freetype
gettext-runtime
hicolor-icon-theme
libepoxy
libffi
libpng
libxml2
lmdb
openssl
pixman
win-iconv
zlib

The following items failed to build:
fontconfig

The following items were not built because one or more of the other items failed to build:
atk
cairo
cyrus-sasl
enchant
gdk-pixbuf
glib
glib-networking
gsettings-desktop-schemas
gtk
gtk3
harfbuzz
libcroco
librsvg
libsoup
pango
...
It seems that the library 'fontconfig' is not supported for compiling vc14 because of an error (see. [fontconfig_error_vc14.txt](https://www.dropbox.com/s/8a1pzm6plf6pa27/fontconfig_error_vc14.txt?dl=0))

**Comment by pbor** [comment]
try to change the file

fontconfig/config.h

It has a line 

#define snprintf _snprintf

change to something like

#ifndef snprintf
#define snprintf _snprintf
#endif
 

Note that you will need to remove the "build" and "gtk" dir and restart the build

**Comment by INTITY** [comment]
This method does not work (see. [fontconfig_error_vc14_2.txt](https://www.dropbox.com/s/9445nle7f3nltlf/fontconfig_error_vc14_2.txt?dl=0))

**Comment by pbor** [comment]
well, the error is now different so it seems to have sorted some kind of effect... can you post the full log for the build failure?

**Comment by INTITY** [comment]
This is a known bug compilation vc14 ([fatal error C1189: #error: Macro definition of snprintf conflicts with Standard Library function declaration](http://stackoverflow.com/questions/27754492/vs-2015-compiling-cocos2d-x-3-3-error-fatal-error-c1189-error-macro-definiti)).

Full report compilation [build_vc14_1.txt](https://www.dropbox.com/s/brhkhczv4agns2p/build_vc14_1.txt?dl=0)

**Comment by pbor** [comment]
I see... then try to completely remove that line.
Later we can find a proper ifdef
Il 15/Gen/2016 19:56, "Vite" <notifications@github.com> ha scritto:

**Comment by INTITY** [comment]
Good. I'll post a report for library developers 'fontconfig'.

**Comment by INTITY** [comment]
I did not notice the existing directive '#define printf printf' ([# 35](https://github.com/wingtk/gtk-win32/blob/master/fontconfig/config.h#L35)) in the file 'config.h'. I added a condition to downgrade MSVC:

`#if _MSC_VER < 1900`
`#define snprintf _snprintf`
`#endif`

Full report compilation: [build_vc14_2.txt](https://www.dropbox.com/s/xouvonzhcrnp23v/build_vc14_2.txt?dl=0)

**Comment by INTITY** [comment]
Error compiling libraries 'glib':
`fatal error C1083: Cannot open include file: 'libintl.h'`
It seems the header file 'libintl.h' does not exist.

**Comment by INTITY** [comment]
Error compiling libraries 'enchant': [enchant_error_vc14.txt](https://www.dropbox.com/s/q7dlo69tdbk8ms8/enchant_error_vc14.txt?dl=0)
Full report compilation: [build_vc14_3.txt](https://www.dropbox.com/s/cqvoxeq4d4ykfje/build_vc14_3.txt?dl=0)

**Comment by pbor** [comment]
Yeah, looking at what the hexchat guys did here https://github.com/hexchat/gtk-win32/commit/2f3c96d1bda318a9cdf2a85d80e9a838c5b850ae I think you need to drop the "_W64" (I am not sure what it is exactly)

**Comment by nacho** [comment]
This is superseded by https://github.com/wingtk/gtk-win32/issues/52
