### ISSUE TITLE
Support multiple msvc versions

### ISSUE THREAD

**Issue by nzjrs** [wingtk/gtk-win32#2]
To work with upstream Python, the stack needs to be build with VS2010 for 2.7 > Python <= 3.4.

Inital work in this direction is seen here https://github.com/nice-software/gtk-win32/tree/wip/upstream-msvc

**Comment by pbor** [comment]
Hi John!

I am not opposed to this, though we are targeting VS2013.

Can you provide a link that mention that requirements for upstream Python?

**Comment by nzjrs** [comment]
Hi!

https://docs.python.org/devguide/setup.html#windows goes through the MSVC versions used to build python. 
 * Python 3.5 and later use Microsoft Visual Studio 2015.
 * Python 3.3 and 3.4 use Microsoft Visual Studio 2010. 
 * Most Python versions prior to 3.3 use Microsoft Visual Studio 2008

https://docs.python.org/3/extending/windows.html#building-on-windows says "Notice that you should use the same version of VC++that was used to build Python itself".

In past I have had trouble when this is not the case. There is a bit of a thread discussing some issues here http://www.gossamer-threads.com/lists/python/dev/1005737

If you control the world then you can distribute native extensions along with your own version of Python (hence why some people distribute their entire python application and interpreter built using MSVC). Some people are not aware of these issues and their programs just behave weird or crash.

I intend to build Python wheels that I can distribute in the correct Python fashion, so I certainly need to use the correct compiler.

**Comment by nacho** [comment]
As from the name of the issue we currently support vs12 and vs14 so we can close this already.
