### ISSUE TITLE
fontconfig url returns "Not Found"

### ISSUE THREAD

**Issue by anthrotype** [wingtk/gtk-win32#20]
The fontconfig url in build.ps1 no longer works: 
http://fontconfig.org/release/fontconfig-2.11.1.tar.gz

It should be replaced by something like this:
https://www.freedesktop.org/software/fontconfig/release/fontconfig-2.11.1.tar.gz

**Comment by nacho** [comment]
Can you create a pull request so you get the proper credit?

**Comment by anthrotype** [comment]
sure!
