### ISSUE TITLE
Error loading file 'sqlite-autoconf-3120000.tar.gz'

### ISSUE THREAD

**Issue by intity** [wingtk/gtk-win32#27]
Compilation error, can not download the file: https://www.sqlite.org/2016/sqlite-autoconf-3120000.tar.gz
ERROR 404: Not Found.

**Comment by nacho** [comment]
This is fixed in https://github.com/wingtk/gtk-win32/commit/1ce765eb783ecc0bb2b7ea2c27cc35aa3ef4c20d
