### ISSUE TITLE
Use upstream win32 build files

### ISSUE THREAD

**Issue by nzjrs** [wingtk/gtk-win32#3]
For all of the G* stack we should use Fan's (upstream) solutions. The main changes the hexchat folks made are

 * a global stack.props controlling things like optomisation level
 * the output directory

IMO the output directory should be left as is and the packaging step of build.ps should be updated to reflect Fan's conventions.

This is related to #2 as they will both likely be solved at the same time.

**Comment by pbor** [comment]
I agree that we should try to stick to Fan's upstream version as much as possible.

**Comment by Sineaggi** [comment]
The build files of atk, gdk-pixbuf, glib-networking, glib, gtk, gtk3, and pango can all be safely removed, as long as `$GlibEtcInstallRoot` is properly overridden in those solution files.

From what I can tell, it's as simple as adding `/p:GlibEtcInstallRoot=$BuildDirectory\gtk\$Configuration` to each msbuild call for g* libraries.

For example, change `Exec msbuild build\win32\vs$VSVer\atk.sln /p:Platform=$platform /p:Configuration=Release /maxcpucount /nodeReuse:True` to `Exec msbuild build\win32\vs$VSVer\atk.sln /p:Platform=$platform /p:Configuration=Release /p:GlibEtcInstallRoot=$BuildDirectory\gtk\$Configuration /maxcpucount /nodeReuse:True`.

**Comment by Sineaggi** [comment]
Although Fan's solution files expect intl.dll and intl.lib, not libintl. In the CMakeLists.txt file for gettext-runtime, there's a line that does this renaming.
```
if(MSVC)
set_target_properties(intl PROPERTIES OUTPUT_NAME "libintl")
endif(MSVC)
```
We should probably consider choosing either libintl or intl, because that'll affect how the rest of the libraries are linked.

I vote for intl, sans the lib prefix.

**Comment by Sineaggi** [comment]
Pull request #15 should fix the intl vs libintl issue.

**Comment by pbor** [comment]
I used /p:GlibEtcInstallRoot=$BuildDirectory\gtk\$Configuration for libcroco and librsvg and seems to work as expected.

We should definitely try to do the same for all the other modules with Fan's projects

**Comment by nacho** [comment]
A bit of progress on this. I managed to migrate from the custom visual studio projects to the upstream cmake or nmake scripts.

**Comment by nacho** [comment]
Most of the projects use the upstream projects now. Let's close this for now.
