### ISSUE TITLE
gtk3-demo crashed on 'Tool Palette' example.

### ISSUE THREAD

**Issue by accel2k** [wingtk/gtk-win32#31]
Both versions (x86, x64) are vulnerable. Compiled with Visual Studio Professional 2013.

Call stack:
>	glib-2.0.dll!g_str_hash(const void * v) Line 1876	C
 	glib-2.0.dll!g_hash_table_lookup_node(_GHashTable * hash_table, const void * key, unsigned int * hash_return) Line 375	C
 	glib-2.0.dll!g_hash_table_replace(_GHashTable * hash_table, void * key, void * value) Line 1278	C
 	gtk-3-3.0.dll!gtk_icon_theme_list_contexts(_GtkIconTheme * icon_theme) Line 2676	C
 	gtk3-demo.exe!load_icon_items(_GtkToolPalette * palette) Line 647	C
 	gtk3-demo.exe!do_toolpalette(_GtkWidget * do_widget) Line 525	C
 	gtk3-demo.exe!run_example_for_row(_GtkWidget * window, _GtkTreeModel * model, _GtkTreeIter * iter) Line 128	C
 	gtk3-demo.exe!row_activated_cb(_GtkWidget * tree_view, _GtkTreePath * path, _GtkTreeViewColumn * column) Line 945	C
 	gtk-3-3.0.dll!_gtk_marshal_VOID__BOXED_OBJECT(_GClosure * closure, _GValue * return_value, unsigned int n_param_values, const _GValue * param_values, void * invocation_hint, void * marshal_data) Line 3170	C
 	gobject-2.0.dll!g_closure_invoke(_GClosure * closure, _GValue * return_value, unsigned int n_param_values, const _GValue * param_values, void * invocation_hint) Line 808	C
 	gobject-2.0.dll!signal_emit_unlocked_R(_SignalNode * node, unsigned int detail, void * instance, _GValue * emission_return, const _GValue * instance_and_params) Line 3635	C
 	gobject-2.0.dll!g_signal_emit_valist(void * instance, unsigned int signal_id, unsigned int detail, char * var_args) Line 3385	C
 	gobject-2.0.dll!g_signal_emit(void * instance, unsigned int signal_id, unsigned int detail, ...) Line 3441	C
 	gtk-3-3.0.dll!gtk_tree_view_row_activated(_GtkTreeView * tree_view, _GtkTreePath * path, _GtkTreeViewColumn * column) Line 12623	C
 	gtk-3-3.0.dll!gtk_tree_view_multipress_gesture_pressed(_GtkGestureMultiPress * gesture, int n_press, double x, double y, _GtkTreeView * tree_view) Line 3370	C
 	gobject-2.0.dll!ffi_call_win32(unsigned long * ffi_prep_args, unsigned long * ecif, unsigned long cif_abi, unsigned long cif_bytes, unsigned long cif_flags, unsigned long * rvalue, unsigned long * fn) Line 965	Unknown
 	gobject-2.0.dll!ffi_call(ffi_cif * cif, void (void) * fn, void * rvalue, void * * avalue) Line 404	C
 	gobject-2.0.dll!g_cclosure_marshal_generic_va(_GClosure * closure, _GValue * return_value, void * instance, char * args_list, void * marshal_data, int n_params, unsigned int * param_types) Line 1607	C
 	gobject-2.0.dll!_g_closure_invoke_va(_GClosure * closure, _GValue * return_value, void * instance, char * args, int n_params, unsigned int * param_types) Line 871	C
 	gobject-2.0.dll!g_signal_emit_valist(void * instance, unsigned int signal_id, unsigned int detail, char * var_args) Line 3300	C
 	gobject-2.0.dll!g_signal_emit(void * instance, unsigned int signal_id, unsigned int detail, ...) Line 3441	C
 	gtk-3-3.0.dll!gtk_gesture_multi_press_begin(_GtkGesture * gesture, _GdkEventSequence * sequence) Line 243	C
 	gobject-2.0.dll!g_cclosure_marshal_VOID__BOXEDv(_GClosure * closure, _GValue * return_value, void * instance, char * args, void * marshal_data, int n_params, unsigned int * param_types) Line 1953	C
 	gobject-2.0.dll!_g_closure_invoke_va(_GClosure * closure, _GValue * return_value, void * instance, char * args, int n_params, unsigned int * param_types) Line 871	C
 	gobject-2.0.dll!g_signal_emit_valist(void * instance, unsigned int signal_id, unsigned int detail, char * var_args) Line 3300	C
 	gobject-2.0.dll!g_signal_emit(void * instance, unsigned int signal_id, unsigned int detail, ...) Line 3441	C
 	gtk-3-3.0.dll!_gtk_gesture_check_recognized(_GtkGesture * gesture, _GdkEventSequence * sequence) Line 389	C
 	gtk-3-3.0.dll!gtk_gesture_handle_event(_GtkEventController * controller, const _GdkEvent * event) Line 747	C
 	gtk-3-3.0.dll!gtk_gesture_single_handle_event(_GtkEventController * controller, const _GdkEvent * event) Line 221	C
 	gtk-3-3.0.dll!gtk_event_controller_handle_event(_GtkEventController * controller, const _GdkEvent * event) Line 231	C
 	gtk-3-3.0.dll!_gtk_widget_run_controllers(_GtkWidget * widget, const _GdkEvent * event, GtkPropagationPhase phase) Line 7328	C
 	gtk-3-3.0.dll!gtk_widget_real_motion_event(_GtkWidget * widget, _GdkEventMotion * event) Line 7104	C
 	gtk-3-3.0.dll!_gtk_marshal_BOOLEAN__BOXEDv(_GClosure * closure, _GValue * return_value, void * instance, char * args, void * marshal_data, int n_params, unsigned int * param_types) Line 133	C
 	gobject-2.0.dll!_g_closure_invoke_va(_GClosure * closure, _GValue * return_value, void * instance, char * args, int n_params, unsigned int * param_types) Line 871	C
 	gobject-2.0.dll!g_signal_emit_valist(void * instance, unsigned int signal_id, unsigned int detail, char * var_args) Line 3300	C
 	gobject-2.0.dll!g_signal_emit(void * instance, unsigned int signal_id, unsigned int detail, ...) Line 3441	C
 	gtk-3-3.0.dll!gtk_widget_event_internal(_GtkWidget * widget, _GdkEvent * event) Line 7704	C
 	gtk-3-3.0.dll!gtk_widget_event(_GtkWidget * widget, _GdkEvent * event) Line 7263	C
 	gtk-3-3.0.dll!propagate_event_up(_GtkWidget * widget, _GdkEvent * event, _GtkWidget * topmost) Line 2545	C
 	gtk-3-3.0.dll!propagate_event(_GtkWidget * widget, _GdkEvent * event, int captured, _GtkWidget * topmost) Line 2648	C
 	gtk-3-3.0.dll!gtk_propagate_event(_GtkWidget * widget, _GdkEvent * event) Line 2682	C
 	gtk-3-3.0.dll!gtk_main_do_event(_GdkEvent * event) Line 1878	C
 	gdk-3-3.0.dll!gdk_event_dispatch(_GSource * source, int (void *) * callback, void * user_data) Line 3664	C
 	glib-2.0.dll!g_main_dispatch(_GMainContext * context) Line 3154	C
 	glib-2.0.dll!g_main_context_iterate(_GMainContext * context, int block, int dispatch, _GThread *) Line 3840	C
 	glib-2.0.dll!g_main_context_iteration(_GMainContext * context, int may_block) Line 3901	C
 	gio-2.0.dll!g_application_run(_GApplication * application, int argc, char * * argv) Line 2381	C
 	gtk3-demo.exe!main(int argc, char * * argv) Line 1180	C
 	[External Code]	
 	[Frames below may be incorrect and/or missing, no symbols loaded for kernel32.dll]

**Comment by nacho** [comment]
Hey, is this with the last version of gtk? 3.20.4?

**Comment by accel2k** [comment]
Hi. Yes, last one from the master branch.

**Comment by nacho** [comment]
There is now a gtk 3.20.6. We should give it a try.

**Comment by accel2k** [comment]
I am just checked 3.22.0 version (9192a4c) and it still crashes at the same point.

**Comment by nacho** [comment]
We should definitely research a bit on this, it seems that it is msvc specific though :(

**Comment by nacho** [comment]
See https://bugzilla.gnome.org/show_bug.cgi?id=773078 for the upstream bug report

**Comment by nacho** [comment]
This is now fixed in gtk master, if something we can backport the patch
