### ISSUE TITLE
Visual Studio 2015 support

### ISSUE THREAD

**Issue by TheZoc** [wingtk/gtk-win32#52]
Hello,

I've added ~20 pull requests to the project. As I could understand from #29, this was required to aid in merging.
Most of the work was done by @intity on his pull request, I just fixed some problems that I found and submitted a pull request for each project separately.

From what I could gather, everything should work, except GTK3, where I'm getting the error C1001.
I'm using Visual Studio 2015 Update 2.

[Gist for the output](https://gist.github.com/TheZoc/ef869821410d9811a3487b4ebf369aed) of the command line.

I hope this helps to speed up the merging process and add support to VS2015 :smile: 
I'm anxious to use GTK on Windows :grinning:

**Comment by nacho** [comment]
I merged most of your patches. A couple of them are missing though. libcroco seems to be missing files and librsvg depends on libcroco so I will merge it after it.

**Comment by nacho** [comment]
Everything is now merged, thanks for the patches. Now we should find out what is wrong. See that the hexchat team already has it working with VS 2015 so we could have a look at what is different.

**Comment by TheZoc** [comment]
I'm glad I could be helpful.
I was trying to learn GTK today, so I'm not sure if I could be of any help.

One thing that I think it's good to mention is that I edited libepoxy project file. Before, it was complaining it couldn't be compiled with /OPT:NOREF and /LTCG:INCREMENTAL as they are mutually exclusive.

I added the option ```<LinkTimeCodeGeneration>UseLinkTimeCodeGeneration</LinkTimeCodeGeneration>```

The ```C1001``` error can be thanks to mismatched optimizations.

I already fought a lot with the code for today and I need some rest. I hope this can provide a starting point to add compatibility with VS2015 :grinning:

**Comment by nacho** [comment]
Adding @intity here since he probably checked the stuff already

**Comment by intity** [comment]
@TheZoc please check the latest update Visual Studio 2015. I have not found a compilation error the project `libepoxy`.

**Comment by TheZoc** [comment]
Oh, my apologies, I completely forgot about all of this.
I gave up trying to use gtk-win32... I had to create a visual application to my [patcher system ](https://github.com/TheZoc/ZPatcher) and with the issues I was having, I decided to go with wxWidgets.

Sadly, with my bad luck, my VGA fried last night, so I won't be able to do much until it's replaced. After that, I can do specific tests as you need them and hopefully use this framework in the future 😄

**Comment by nacho** [comment]
vs 2015 seems to do well now. I am closing this now. If something specific issues can be created.
