### ISSUE TITLE
Error build the 'glib' solution for vs14

### ISSUE THREAD

**Issue by intity** [wingtk/gtk-win32#60]
Error build the 'glib' solution for Visual Studio 2015

`
LINK : fatal error LNK1181: cannot open input file '\lib\intl.lib' [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gmodule.vcxproj]
`
`
LINK : fatal error LNK1181: cannot open input file '\lib\intl.lib' [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gthread.vcxproj]
`
`
LINK : fatal error LNK1181: cannot open input file '\lib\intl.lib' [C:\gtk-build\build\x64\release\glib\build\win32\vs14\glib-genmarshal.vcxproj]
`
`
c:\gtk-build\build\x64\release\glib\glib\glibintl.h(16): fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gspawn-win32-helper.vcxproj]
`
`
c:\gtk-build\build\x64\release\glib\glib\glibintl.h(16): fatal error C1083: Cannot open include file: 'libintl.h': No such file or directory [C:\gtk-build\build\x64\release\glib\build\win32\vs14\gspawn-win32-helper-console.vcxproj]
`

**Comment by nacho** [comment]
this is now merged
