### ISSUE TITLE
Error build the gtk solution for vs14

### ISSUE THREAD

**Issue by intity** [wingtk/gtk-win32#63]
Error build the 'gtk' solution for Visual Studio 2015

`
..\..\..\gtk\updateiconcache.c : fatal error C1083: Cannot open include file: 'msvc_recommended_pragmas.h': No such file or directory [C:\gtk-build\build\x64\release\gtk\build\win32\vs14\gtk-update-icon-cache.vcxproj]
`

**Comment by nacho** [comment]
This sounds like it is not finding the includes from glib properly...

**Comment by intity** [comment]
I compiled the 'gtk' solution by hand, and I have not encountered an error. I can not determine the cause.

**Comment by intity** [comment]
I think you need to add to a the `gtk-update-icon-cache` project to the `gtk` solution to fix a compilation error. I can prepare to pull request.

**Comment by pbor** [comment]
yes, please

**Comment by nacho** [comment]
Thanks
