### ISSUE TITLE
Build gtk 3.16.x

### ISSUE THREAD

**Issue by nacho** [wingtk/gtk-win32#7]
We are blocked by https://github.com/anholt/libepoxy/pull/35

**Comment by nacho** [comment]
Fixed

**Comment by codekiddy2** [comment]
Hi nacho,
If you're still having problems building libepoxy here is what I did to build it with VS 2015 and then used the lib/dll to build GTK+ 3.16.x

forked libepoxy from here:
https://github.com/Nephatrine/libepoxy

generated VS solution with CMAKE, and ended up with successful compilation of both libepoxy and GTK+ 3.16.x

you also end up with test projects to perform tests against the library once done.

**Comment by pbor** [comment]
Thanks, most of Fan's changes to libepoxy have been merged and we are now able to build as well
