### ISSUE TITLE
Error: lmdb build failed for vs14

### ISSUE THREAD

**Issue by intity** [wingtk/gtk-win32#79]
Error: lmdb build failed for vs14

`
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120 (Platform Toolset = 'v120') cannot be found. To build using the v120 build tools, please install v120 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\gtk-build\build\x64\release\lmdb\libraries\liblmdb\lmdb.vcxproj]
`

I think you need to add the 'build/win32' of root directory to share the (vs12, vs14) solutions inclusive.
I can prepare a pull request.

**Comment by nacho** [comment]
Yes lmdb currently only supports v12, it would be great to improve it so it supports 2015 as well.

**Comment by nacho** [comment]
This can be closed now.
