### ISSUE TITLE
Add gtksourceview 2.x in the bundle

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gtk-win32#8]
It would be nice to add gtksourceview 2.x library in the bundle.
That would solve all my needs for a good GTK 2.x build.

**Comment by nacho** [comment]
I'd be glad to get a patch for this and for gtksourceview 3, though I think that first we would need to add the msvc projects upstream. I think @fanc999 was going to do something about this if I recall.

**Comment by nacho** [comment]
Now gtksourceview upstream made some progress on supporting msvc. Next step will be to get it some msvc projects.

**Comment by nacho** [comment]
We have now a release for GtkSourceView 3 that contains the visual studio projects, at this point it should be very easy to add them here.

**Comment by Adriatic1** [comment]
That's a good news, thanks

**Comment by nacho** [comment]
Added gtksourceview3.

**Comment by nacho** [comment]
I am closing this now. If you really want gtksourceview2, somebody will have to make the project files for it so a pull request is more appreciated :)

**Comment by Adriatic1** [comment]
Thank you for your work, I'll work on finishing the port of my app to GTK3.x
