### ISSUE TITLE
Failed to build GTK3 with MSVC X64

### ISSUE THREAD

**Issue by accel2k** [wingtk/gtk-win32#83]
> ...
> Generating GTK+ DBUS Sources...
> '\python' is not recognized as an internal or external command,
> operable program or batch file.
>...

We need to define PythonPathX64 variable in "gtk3/build/win32/ * /gtk3-version-paths.props".
It used to generate "gtk\gtkdbusgenerated.*" files during build.

[gtk3-python-path-x64.txt](https://github.com/wingtk/gtk-win32/files/489635/gtk3-python-path-x64.txt)

**Comment by nacho** [comment]
Can you provide a pull request?

**Comment by accel2k** [comment]
Done.

**Comment by nacho** [comment]
We can close this now. Thanks
