### ISSUE TITLE
Default patches dir

### ISSUE THREAD

**Issue by guruDanny67** [wingtk/gtk-win32#87]
I try to implement the hash check on the tarballs and I'm learning git so I have a lot of dirs under c:\gtk-build\github.
If you don't pass the --patches-root-dir parameter the script use (build-dir)\github\gtk-win32 while the option helps says 'The directory where you checked out ...' and this generate an error when I removed the gtk-win32 dir to have only mine.
If I have the correct one if I launch the build in an other checkout of the stack the system gets the parameters always from the gtk-win32 dir and this can lead to error or mistakes if someone wants to get different versions of the script.
The solution is really simple (just add '--patches-root-dir .' on the command line) but is not more correct use, as a default, the same directory of the build.py script ?

Thank in advance
    Daniele Forghieri

**Comment by nacho** [comment]
Feel free to provide a patch for this

**Comment by guruDanny67** [comment]
Thanks which is the preferred way to submit a patch ? 

This is very simple (only a single line changed). I created the .patch file with TortoiseGit but I can't attach it to the issue. I need to make a pull request ?

**Comment by nacho** [comment]
Yeah, a pull request is the preferred way

**Comment by guruDanny67** [comment]
Created the pull request.
