### ISSUE TITLE
No default icons shipped

### ISSUE THREAD

**Issue by Adriatic1** [wingtk/gtk-win32#90]
I've built my program with GTK3 stack, it seems to be running OK.
The issue here is that the default GTK stock icons seem to be missing, and that "hicolor-icon-theme" package is empty, shipping only gtk3-demo.png icon.
I get GTK warnings as in this example:
"Error loading theme icon 'edit-cut' for stock: Icon 'edit-cut' not present in theme Adwaita"

Are stock icons deprecated? Can we ship some standard set of icons within this package?
I tried to install "gnome-icon-theme" (to have something at least) but it is not supported here...

Any advice?

Best regards,
  Miroslav

**Comment by nacho** [comment]
Hey, just build adwaita-icon-theme

**Comment by Adriatic1** [comment]
Thanks! I can confirm that this fixes the issue.
IMO, it would make sense to add "adwaita-icon-theme" as a dependency to GTK3, because without it, you won't even have correct buttons for Window close/minimize/maximize.

**Comment by nacho** [comment]
I guess it depends on the use case, on my one I use some parts of gtk that do not need icons and adding the icons would explode the size. Thanks for the feedback

**Comment by Adriatic1** [comment]
OK, that makes sense too. Thanks for the help.
