### ISSUE TITLE
cairo build failed

### ISSUE THREAD

**Issue by congzhangzh** [wingtk/gtk-win32#91]
build environment:

Windows 10+Visual Studio 2015

Expect: 

After follow https://github.com/wingtk/gtk-win32 I should build gtk3 succ!

Actual:
Failed at cairo build step.

What I Do:
I try to dig the problem and found a one thing I don't understand .

As line:1266@build.py         self.exec_vs(r'make -f Makefile.win32 pixman CFG=%(configuration)s ' + optimizations, add_path=add_path)

is this right? or should be nmake based?

**Comment by congzhangzh** [comment]
just pixman and cairo project use make but not nmake, is this depend on special decision?
how mix make with cl works?

**Comment by nacho** [comment]
well It is not a problem to use make, cairo and pixman they are providing the make scripts for building with it. What error do you get? Did you install make in msys2? Double check the deps you need to install with pacman

**Comment by congzhangzh** [comment]
Tks, I check the code again, code should be ok, I will use a new windows 7 machine test again:)

**Comment by nacho** [comment]
so, does it work?

**Comment by nacho** [comment]
No answer so I am closing this issue. Feel free to reopen if you give more details
